version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: globallogix
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: egor
    deploy:
      replicas: 1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - global-logix-network

  redis-cache:
    image: redis:7-alpine
    deploy:
      replicas: 1
    ports:
      - "6379:6379"
    networks:
      - global-logix-network

  kafka:
    image: 'apache/kafka:3.7.0'
    deploy:
      replicas: 1
    ports:
      - '9092:9092'
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_NUM_PARTITIONS=3
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
    networks:
      - global-logix-network

  auth-service:
    image: epapakin/friendlivery-auth:latest
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/globallogix
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: egor
      SPRING_DATA_REDIS_HOST: redis-cache
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_TIMEOUT: 2000ms
      SERVER_PORT: 8080
    networks:
      - global-logix-network

  delivery-service:
    image: epapakin/friendlivery-delivery:latest
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M
      restart_policy:
        condition: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/globallogix
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: egor
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_REDIS_HOST: redis-cache
      SPRING_REDIS_PORT: 6379
      SERVER_PORT: 8080
    networks:
      - global-logix-network

  flight-service:
    image: epapakin/friendlivery-flight:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/globallogix
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: egor
      SPRING_REDIS_HOST: redis-cache
      SPRING_REDIS_PORT: 6379
      SERVER_PORT: 8080
    networks:
      - global-logix-network

  payment-service:
    image: epapakin/friendlivery-payment:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/globallogix
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: egor
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_REDIS_HOST: redis-cache
      SPRING_REDIS_PORT: 6379
      SERVER_PORT: 8080
    networks:
      - global-logix-network

  notifications-service:
    image: epapakin/friendlivery-notifications:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/globallogix
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: egor
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_REDIS_HOST: redis-cache
      SPRING_REDIS_PORT: 6379
      SPRING_DATA_REDIS_TIMEOUT: 5000ms
      SERVER_PORT: 8080
    networks:
      - global-logix-network

  chat-service:
    image: epapakin/friendlivery-chat:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/globallogix
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: egor
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_REDIS_HOST: redis-cache
      SPRING_REDIS_PORT: 6379
      SERVER_PORT: 8080
    networks:
      - global-logix-network

  api-gateway:
    image: epapakin/friendlivery-gateway:latest
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_REDIS_HOST: redis-cache
      SPRING_REDIS_PORT: 6379
      SERVER_PORT: 8080
    networks:
      - global-logix-network

volumes:
  postgres_data:

networks:
  global-logix-network:
    driver: overlay
    attachable: true